version: '3'

services:

  fastapi:
    container_name: fastapi
    build: fastapi/
    restart: always
    volumes:
      - ./fastapi/:/app
    ports:
      - "80:80"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/initdb/:/docker-entrypoint-initdb.d
      - ./postgres/data/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres_db

volumes:
  pgadmin-data: